# Generated by Django 2.1.5 on 2019-02-13 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_count', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
    ]
